import type {
  MenuItem,
  Ingredient,
  Vendor,
  Recipe,
  StaffMember,
  ShiftEntry,
  TicketOrder,
  Ticket,
} from "./types";

// Demo-grade shared PIN, same for every account (not real auth). A manager
// settings screen to change this is a reasonable follow-up if ever needed.
export const STAFF_PIN = "123";

export const seedMenu: MenuItem[] = [
  // Starters
  {
    id: "m1",
    name: "Samosa (3pc)",
    aliases: ["samos", "sambusa"],
    category: "Starters",
    price: 300,
    veg: false,
    available: true,
    addOns: [{ name: "Extra chili sauce", price: 0 }],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Chicken_samosas_and_lemon_slices.jpg/330px-Chicken_samosas_and_lemon_slices.jpg",
  },
  {
    id: "m2",
    name: "Vegetable Spring Rolls",
    aliases: ["spring roll", "veggie rolls"],
    category: "Starters",
    price: 350,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Golden_Vegetable_Spring_Rolls_Served_with_Dipping_Sauce.jpg/330px-Golden_Vegetable_Spring_Rolls_Served_with_Dipping_Sauce.jpg",
  },
  {
    id: "m3",
    name: "Chicken Wings",
    aliases: ["wings", "kuku wings"],
    category: "Starters",
    price: 600,
    veg: false,
    available: true,
    spiceLevels: ["Mild", "Medium", "Hot"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Chicken_Wings_%287069003341%29.jpg/330px-Chicken_Wings_%287069003341%29.jpg",
  },
  {
    id: "m4",
    name: "Bhajia",
    aliases: ["potato bhajia", "crisps"],
    category: "Starters",
    price: 250,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Fritters.jpg/330px-Fritters.jpg",
  },
  {
    id: "m5",
    name: "Kachumbari Salad",
    aliases: ["salad", "kachumbari"],
    category: "Starters",
    price: 200,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Kachumbari.jpg/330px-Kachumbari.jpg",
  },
  // Mains
  {
    id: "m6",
    name: "Ugali with Sukuma & Beef Stew",
    aliases: ["ugali", "ugali sukuma", "ugali beef"],
    category: "Mains",
    price: 550,
    veg: false,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Ugali_beef_stew_with_sukuma_n_fresh_tomatoes_taken_in_Nanyuki%2C_Kenya.jpg/330px-Ugali_beef_stew_with_sukuma_n_fresh_tomatoes_taken_in_Nanyuki%2C_Kenya.jpg",
  },
  {
    id: "m7",
    name: "Pilau",
    aliases: ["pilau rice", "spiced rice"],
    category: "Mains",
    price: 500,
    veg: false,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Swahili_Pilau.jpg/330px-Swahili_Pilau.jpg",
  },
  {
    id: "m8",
    name: "Chapati & Beans",
    aliases: ["chapo", "chapo beans"],
    category: "Mains",
    price: 400,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Chapati_and_maharage.jpg/330px-Chapati_and_maharage.jpg",
  },
  {
    id: "m9",
    name: "Beef Biryani",
    aliases: ["biryani", "biriani"],
    category: "Mains",
    price: 650,
    veg: false,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Short_rib_biryani%2C_Oasis_Hotel_and_Guest_House%2C_Voi%2C_2025_%2801%29.jpg/330px-Short_rib_biryani%2C_Oasis_Hotel_and_Guest_House%2C_Voi%2C_2025_%2801%29.jpg",
    available: true,
    spiceLevels: ["Mild", "Medium", "Hot"],
  },
  {
    id: "m10",
    name: "Vegetable Curry & Rice",
    aliases: ["veg curry", "curry rice"],
    category: "Mains",
    price: 450,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Vegetable_curry_rice_%2814974664885%29.jpg/330px-Vegetable_curry_rice_%2814974664885%29.jpg",
  },
  {
    id: "m11",
    name: "Grilled Tilapia & Ugali",
    aliases: ["fish", "tilapia", "samaki"],
    category: "Mains",
    price: 750,
    veg: false,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Fried_Tilapia%2C_Ugali%2C_Sukuma_Wiki_and_Kachumbari_%28From_Kisumu%29.JPG/330px-Fried_Tilapia%2C_Ugali%2C_Sukuma_Wiki_and_Kachumbari_%28From_Kisumu%29.JPG",
  },
  // Grills
  {
    id: "m12",
    name: "Nyama Choma (Goat, 1kg)",
    aliases: ["nyama choma", "goat meat", "choma"],
    category: "Grills",
    price: 1800,
    veg: false,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Nyama_choma_ya_mbuzi.jpg/330px-Nyama_choma_ya_mbuzi.jpg",
  },
  {
    id: "m13",
    name: "Grilled Chicken Half",
    aliases: ["chicken", "kuku choma"],
    category: "Grills",
    price: 700,
    veg: false,
    available: true,
    spiceLevels: ["Mild", "Medium", "Hot"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flame-grilled_PERi-PERi_chicken.jpg/330px-Flame-grilled_PERi-PERi_chicken.jpg",
  },
  {
    id: "m14",
    name: "Mixed Grill Platter",
    aliases: ["mixed grill", "platter", "grill combo"],
    category: "Grills",
    price: 2200,
    veg: false,
    available: true,
    comboTag: "Combo",
    comboComponents: [
      { name: "Grilled Chicken", qty: "1/2 chicken" },
      { name: "Beef Sausages", qty: "4 pieces" },
      { name: "Grilled Ribs", qty: "300g" },
      { name: "Kachumbari", qty: "1 serving" },
      { name: "Ugali", qty: "2 servings" },
    ],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Mixed_grill_on_sizzling_plate.JPG/330px-Mixed_grill_on_sizzling_plate.JPG",
  },
  {
    id: "m15",
    name: "Grilled Pork Chops",
    aliases: ["pork", "pork chops"],
    category: "Grills",
    price: 900,
    veg: false,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Grilled_pork_chops.jpg/330px-Grilled_pork_chops.jpg",
  },
  // Beverages
  {
    id: "m16",
    name: "Tusker Lager",
    aliases: ["tusker", "beer"],
    category: "Beverages",
    price: 300,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Tusker_Lager.jpg/330px-Tusker_Lager.jpg",
  },
  {
    id: "m17",
    name: "Fresh Passion Juice",
    aliases: ["passion juice", "juice"],
    category: "Beverages",
    price: 250,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Passion_Fruit_juice.jpg/330px-Passion_Fruit_juice.jpg",
  },
  {
    id: "m18",
    name: "Dawa Cocktail",
    aliases: ["dawa", "cocktail"],
    category: "Beverages",
    price: 550,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Dawa_at_the_Carnivore_Restaurant_01.jpg/330px-Dawa_at_the_Carnivore_Restaurant_01.jpg",
  },
  {
    id: "m19",
    name: "Kenyan Coffee",
    aliases: ["coffee", "kahawa"],
    category: "Beverages",
    price: 200,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Java_Coffee.jpg/330px-Java_Coffee.jpg",
  },
  {
    id: "m20",
    name: "Soda (350ml)",
    aliases: ["soda", "coke", "fanta", "sprite"],
    category: "Beverages",
    price: 150,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Fanta_Orange_Glass_Bottle.jpg/330px-Fanta_Orange_Glass_Bottle.jpg",
  },
  {
    id: "m21",
    name: "Mineral Water",
    aliases: ["water"],
    category: "Beverages",
    price: 150,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Bottled_water_%286972595593%29.jpg/330px-Bottled_water_%286972595593%29.jpg",
  },
  // Desserts
  {
    id: "m22",
    name: "Mandazi (3pc)",
    aliases: ["mandazi", "donut"],
    category: "Desserts",
    price: 200,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Bowl_of_mandazi.jpg/330px-Bowl_of_mandazi.jpg",
  },
  {
    id: "m23",
    name: "Chocolate Fudge Cake",
    aliases: ["cake", "chocolate cake"],
    category: "Desserts",
    price: 400,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Chocolate_fudge_cake.jpg/330px-Chocolate_fudge_cake.jpg",
  },
  {
    id: "m24",
    name: "Vanilla Ice Cream",
    aliases: ["ice cream"],
    category: "Desserts",
    price: 300,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Vanilla_ice_cream_cone.JPG/330px-Vanilla_ice_cream_cone.JPG",
  },
  {
    id: "m25",
    name: "Fruit Salad",
    aliases: ["fruits", "fruit"],
    category: "Desserts",
    price: 300,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Fruit_salad_flanked_by_Sabre_flatware.jpg/330px-Fruit_salad_flanked_by_Sabre_flatware.jpg",
  },
  // Additional Starters
  {
    id: "m26",
    name: "Beef Mishkaki Skewers",
    aliases: ["mishkaki", "skewers", "beef skewers"],
    category: "Starters",
    price: 450,
    veg: false,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Mishkaki_at_Coco_Beach%2C_Oysterbay..jpg/330px-Mishkaki_at_Coco_Beach%2C_Oysterbay..jpg",
  },
  {
    id: "m27",
    name: "Onion Rings",
    aliases: ["onion rings"],
    category: "Starters",
    price: 280,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Beer_Battered_Onion_Rings_%287306368212%29.jpg/330px-Beer_Battered_Onion_Rings_%287306368212%29.jpg",
  },
  // Additional Mains
  {
    id: "m28",
    name: "Matoke (Plantain Stew)",
    aliases: ["matoke", "plantain", "green banana stew"],
    category: "Mains",
    price: 480,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Matoke-Meat_Stew-Sukuma_Wiki.jpg/330px-Matoke-Meat_Stew-Sukuma_Wiki.jpg",
  },
  {
    id: "m29",
    name: "Coconut Fish Curry & Rice",
    aliases: ["fish curry", "coconut curry"],
    category: "Mains",
    price: 700,
    veg: false,
    available: true,
    spiceLevels: ["Mild", "Medium", "Hot"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Fish_curry_Rice_plate_%2813476259935%29.jpg/330px-Fish_curry_Rice_plate_%2813476259935%29.jpg",
  },
  // Additional Grills
  {
    id: "m30",
    name: "Grilled Beef Ribs",
    aliases: ["ribs", "beef ribs"],
    category: "Grills",
    price: 950,
    veg: false,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Interstate_Beef_Ribs.jpg/330px-Interstate_Beef_Ribs.jpg",
  },
  {
    id: "m31",
    name: "BBQ Chicken Wings",
    aliases: ["bbq wings", "grilled wings"],
    category: "Grills",
    price: 650,
    veg: false,
    available: true,
    spiceLevels: ["Mild", "Medium", "Hot"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Bbq_chicken_wings.JPG/330px-Bbq_chicken_wings.JPG",
  },
  // Additional Beverages
  {
    id: "m32",
    name: "Iced Tea",
    aliases: ["ice tea", "iced tea"],
    category: "Beverages",
    price: 220,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/NCI_iced_tea.jpg/330px-NCI_iced_tea.jpg",
  },
  {
    id: "m33",
    name: "Chocolate Milkshake",
    aliases: ["milkshake", "shake"],
    category: "Beverages",
    price: 350,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Chocolate_milkshake.jpg/330px-Chocolate_milkshake.jpg",
  },
  // Additional Desserts
  {
    id: "m34",
    name: "Baked Cheesecake",
    aliases: ["cheesecake"],
    category: "Desserts",
    price: 450,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg/330px-Baked_cheesecake_with_raspberries_and_blueberries.jpg",
  },
  {
    id: "m35",
    name: "Tropical Fruit Parfait",
    aliases: ["parfait"],
    category: "Desserts",
    price: 350,
    veg: true,
    available: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Yogurt_parfait_with_granola_and_blueberries_in_shot_glasses_with_silverware_spoons_%2817098581522%29.jpg/330px-Yogurt_parfait_with_granola_and_blueberries_in_shot_glasses_with_silverware_spoons_%2817098581522%29.jpg",
  },
];

export const seedIngredients: Ingredient[] = [
  { id: "i1", name: "Unga (Maize Flour)", sku: "UNG-001", packaging: "Bale", quantity: 6, piecesPerPackage: 12, totalCost: 17280, unit: "kg", reorderThreshold: 2, unitCost: 120 },
  { id: "i2", name: "Sukuma Wiki", sku: "SUK-002", packaging: "Crate", quantity: 4, piecesPerPackage: 10, totalCost: 2400, unit: "kg", reorderThreshold: 5, unitCost: 60 },
  { id: "i3", name: "Beef", sku: "BEF-003", packaging: "Carton", quantity: 5, piecesPerPackage: 4, totalCost: 16250, unit: "kg", reorderThreshold: 3, unitCost: 650 },
  { id: "i4", name: "Cooking Oil", sku: "OIL-004", packaging: "Carton (12x2L)", quantity: 3, piecesPerPackage: 12, totalCost: 20160, unit: "litre", reorderThreshold: 2, unitCost: 280 },
  { id: "i5", name: "Rice", sku: "RIC-005", packaging: "Bag", quantity: 7, piecesPerPackage: 1, totalCost: 22680, unit: "kg", reorderThreshold: 3, unitCost: 180 },
  { id: "i6", name: "Whole Chicken", sku: "CHK-006", packaging: "Tray", quantity: 6, piecesPerPackage: 1, totalCost: 4500, unit: "pc", reorderThreshold: 8, unitCost: 750 },
  { id: "i7", name: "Tilapia (fresh)", sku: "FSH-007", packaging: "Iced Tray", quantity: 12, piecesPerPackage: 1, totalCost: 5400, unit: "pc", reorderThreshold: 10, unitCost: 450 },
  { id: "i8", name: "Tomatoes", sku: "TOM-008", packaging: "Crate", quantity: 4, piecesPerPackage: 8, totalCost: 1260, unit: "kg", reorderThreshold: 3, unitCost: 90 },
  { id: "i9", name: "Onions", sku: "ONI-009", packaging: "Net Bag", quantity: 5, piecesPerPackage: 1, totalCost: 1600, unit: "kg", reorderThreshold: 3, unitCost: 80 },
  { id: "i10", name: "Goat Meat", sku: "GTM-010", packaging: "Carton", quantity: 3, piecesPerPackage: 5, totalCost: 12750, unit: "kg", reorderThreshold: 2, unitCost: 850 },
];

export const seedVendors: Vendor[] = [
  { id: "v1", name: "Wangige Grain Millers", category: "Grains & Flour", paymentMethod: "mpesa", lastPaymentAmount: 24000, lastPaymentDate: "2026-08-18" },
  { id: "v2", name: "Kiambu Fresh Greens", category: "Vegetables", paymentMethod: "cash", lastPaymentAmount: 8500, lastPaymentDate: "2026-08-22" },
  { id: "v3", name: "Farmers Choice Butchery", category: "Meat & Poultry", paymentMethod: "mpesa", lastPaymentAmount: 62000, lastPaymentDate: "2026-08-20" },
  { id: "v4", name: "Bidco Oil Distributors", category: "Cooking Oil", paymentMethod: "cash", lastPaymentAmount: 15400, lastPaymentDate: "2026-08-15" },
  { id: "v5", name: "Lake Naivasha Fish Suppliers", category: "Fish", paymentMethod: "mpesa", lastPaymentAmount: 18000, lastPaymentDate: "2026-08-19" },
];

export const seedRecipes: Recipe[] = [
  {
    id: "r1",
    menuItemId: "m6", // Ugali with Sukuma & Beef Stew
    components: [
      { ingredientId: "i1", qty: 0.3 },
      { ingredientId: "i2", qty: 0.2 },
      { ingredientId: "i3", qty: 0.25 },
      { ingredientId: "i4", qty: 0.05 },
    ],
  },
  {
    id: "r2",
    menuItemId: "m9", // Beef Biryani
    components: [
      { ingredientId: "i5", qty: 0.35 },
      { ingredientId: "i3", qty: 0.2 },
      { ingredientId: "i9", qty: 0.1 },
      { ingredientId: "i4", qty: 0.06 },
    ],
  },
  {
    id: "r3",
    menuItemId: "m11", // Grilled Tilapia & Ugali
    components: [
      { ingredientId: "i7", qty: 1 },
      { ingredientId: "i1", qty: 0.25 },
      { ingredientId: "i8", qty: 0.1 },
      { ingredientId: "i4", qty: 0.04 },
    ],
  },
  {
    id: "r4",
    menuItemId: "m12", // Nyama Choma (Goat, 1kg)
    components: [
      { ingredientId: "i10", qty: 1 },
      { ingredientId: "i9", qty: 0.1 },
    ],
  },
  {
    id: "r5",
    menuItemId: "m13", // Grilled Chicken Half
    components: [
      { ingredientId: "i6", qty: 0.5 },
      { ingredientId: "i8", qty: 0.08 },
      { ingredientId: "i9", qty: 0.05 },
    ],
  },
];

// Pay Type / Rate weren't part of the roster supplied — everyone defaults to
// a placeholder monthly rate of 0 until real compensation figures are set.
// Ids use an "st" prefix (rather than continuing "s1".."s9") so they can
// never collide with a staff id an existing browser's persisted tickets
// might still reference from the old placeholder roster.
export const seedStaff: StaffMember[] = [
  { id: "st1", name: "Linda O.", role: "Manager", payType: "monthly", rate: 0, phone: "0723021511" },
  { id: "st2", name: "Halima. K", role: "Manager", payType: "monthly", rate: 0, phone: "0723303712" },
  { id: "st3", name: "Hadija. K", role: "Manager", payType: "monthly", rate: 0, phone: "0748360567" },
  { id: "st4", name: "Nancy Obuya", role: "Cashier", payType: "monthly", rate: 0, phone: "0702491234" },
  { id: "st5", name: "Innocent Bakabwa", role: "Chef", payType: "monthly", rate: 0, phone: "0707792054" },
  { id: "st6", name: "Idah Nyakio", role: "Waiter", payType: "monthly", rate: 0, phone: "0716221718" },
  { id: "st7", name: "Loise Wairimu", role: "Waiter", payType: "monthly", rate: 0, phone: "0705670040" },
  { id: "st8", name: "Collins Odhiambo", role: "Waiter", payType: "monthly", rate: 0, phone: "0725750785" },
  { id: "st9", name: "Sylvia Muthike", role: "Kitchen Assistant", payType: "monthly", rate: 0, phone: "0715703928" },
  { id: "st10", name: "Robin Lukaku", role: "Kitchen Assistant", payType: "monthly", rate: 0, phone: "0704046663" },
  { id: "st11", name: "Ephy Anyango", role: "Kitchen Assistant", payType: "monthly", rate: 0, phone: "0710474882" },
];

// No demo shift/ticket/order history is seeded against this real roster —
// the previous placeholder staff's ids are gone, and there's no ticket/shift
// data to remap onto the new roster, so the app just starts with an empty
// queue that staff populate normally through the UI.
export const seedShifts: ShiftEntry[] = [];

export const seedTickets: Ticket[] = [];

export const seedOrders: Record<string, TicketOrder> = {};
